### ISSUE TITLE
User story idea

### ISSUE THREAD

**Issue by mckenziephagen** [baharsener/visualEyes#11]
Eyelink doesn't write EDFs in real tie, it gets saved when the task ends. The user will have to modify their eyelink experiment to have breaks if wanting to do "real time" QC (@baharsener).

**Comment by BrendaQiu** [comment]
Our lab typically have multiple runs of the same experiment with arbitrary amount of break time in between. We execute the same script once for every run, where one `edf` file is saved after every run. In our use case, we could do QC in between runs, which is pseudo real-time but good enough (we wouldn't want to stop the participant in the middle of a run anyway). It's a pretty standard practice for fMRI studies to have repeated runs of the same experiment, so QC in the middle of the study is totally possible & desired. 

For studies that have no break in the script (e.g. Bahar's study has a break for participants between memory encoding and retrieval, but the script doesn't stop), an easy fix would be to pick a breakpoint (e.g. right after the break starts), terminate the eye-tracking session to save an `edf` file, then re-initialize the eye-tracker. Problem with that is (1) data around the breakpoint might be sacrificed (terminate, save, and reinitialize the eye-tracker take little time, but still a few data points will be lost; if the breakpoint is indeed during a break, it won't matter, otherwise it will), and (2) `edf`s might have to be concatenated later for post-hoc analysis. I wonder if QC during experiment is worth the hassle for this type of design.
